sudo: required

language: bash

services:
    - docker

before_install:
    - make build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD --password-stdin;
      make push-image;
    fi
